# Generated by Django 5.0.6 on 2024-07-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
