# Generated by Django 5.0.6 on 2024-07-30 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_ordered_order_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered',
            new_name='payment_status',
        ),
    ]
